environment:

  matrix:
    - PYTHON: "C:\\Python27"
    - PYTHON: "C:\\Python35"

install:
  # Prepend Python to the PATH of this build.
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"

  # Upgrade to the latest version of pip to avoid it displaying warnings
  # about it being out of date.
  - "python.exe -m pip install --disable-pip-version-check --user --upgrade pip"

  # General Python dev requirements
  - "python.exe -m pip install wheel mock nose coverage"

  # Project requirements
  - "python.exe -m pip install -r requirements.txt"
  - "python.exe -m pip install pypiwin32"

build: off

test_script:
  # Start new shell to get valid console when testing.
  - "cmd /C nosetests --with-coverage --cover-package=asciimatics"

after_test:
  - "python.exe setup.py bdist_wheel"

artifacts:
  - path: .coverage

#on_success:
#  You can use this step to upload your artifacts to a public website.
#  See Appveyor's documentation for more details. Or you can simply
#  access your wheels from the Appveyor "artifacts" tab for your build.
